export enum Tech {
  AJV = 'AJV',
  AXIOS = 'Axios',
  BULMA = 'Bulma',
  ESLINT = 'ESLint',
  JSON_SCHEMA = 'JSON Schema',
  NODE = 'Nodejs',
  PINIA = 'Pinia',
  PRETTIER = 'Prettier',
  SASS = 'Sass',
  TS = 'TypeScript',
  VITE = 'Vite',
  VITEST = 'Vitest',
  VUE = 'Vue',
  VUE_ROUTER = 'Vue-Router',
  VUE_TEST_UTILS = 'Vue Test Utils',
}
